### ISSUE TITLE
no BasicType "data" or "object"

### ISSUE THREAD

**Issue by haraldh** [ctron/varlink-java#1]
https://github.com/ctron/varlink-java/blob/12c273fccde448141520f0499983cfdabaf9e04f/varlink-idl/de.dentrassi.varlink.idl/src/de/dentrassi/varlink/idl/VarlinkIdl.xtext#L64

Hmm, there is no BasicType "data" or "object"

**Comment by ctron** [comment]
I original got that from this page here IIRC: https://github.com/varlink/documentation/wiki/Interface-Definition

It looks a bit different now, but the section [Parsing Expression Grammar](https://github.com/varlink/documentation/wiki/Interface-Definition#parsing-expression-grammar) still has type "data".
